### ISSUE TITLE
paymaster test script is failing 

### ISSUE THREAD

**Issue by aymentrosh** [0xFableOrg/simple-op-stack-rollup#63]
when I try to test the paymaster with `pnpm run test` I get this issue inside the bundler node
```
sage:Error: VM Exception while processing transaction: reverted with custom error 'ValidationResult([2350896, 28000000000000000, false, 1698654474, 1698654774, \"0x\"], [0, 0], [0, 0], [3000000000000000000, 3000])']","logger":"stackup_bundler/client/eth_sendUserOperation","caller":"/home/aymen/go/pkg/mod/github.com/stackup-wallet/stackup-bundler@v0.6.21/pkg/client/client.go:128","time":"2023-10-30T09:27:57+01:00","message":"eth_sendUserOperation error"}
{"level":"info","bundler_mode":"private","client_id":"127.0.0.1","method":"POST","status_code":200,"body_size":3031,"path":"/","latency":"187.962706ms","rpc_method":"eth_sendUserOperation","v":0,"logger":"stackup_bundler/http","caller":"/home/aymen/go/pkg/mod/github.com/stackup-wallet/stackup-bundler@v0.6.21/internal/logger/middleware.go:60","time":"2023-10-30T09:27:57+01:00"}
```

and I get this issue inside the hardhat node 

```
eth_call
  Contract call:       EntryPoint#simulateValidation
  From:                0x0000000000000000000000000000000000000000
  To:                  0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789

  Error: VM Exception while processing transaction: reverted with custom error 'ValidationResult([2350896, 28000000000000000, false, 1698654474, 1698654774, "0x"], [0, 0], [0, 0], [3000000000000000000, 3000])'
      at EntryPoint.handleAggregatedOps (contracts/core/EntryPoint.sol:139)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async HardhatNode.runCall (/home/aymen/karak/account-abstraction/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:679:20)
      at async EthModule._callAction (/home/aymen/karak/account-abstraction/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:366:9)
      at async HardhatNetworkProvider._sendWithLogging (/home/aymen/karak/account-abstraction/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:145:22)
      at async HardhatNetworkProvider.request (/home/aymen/karak/account-abstraction/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:122:18)
      at async JsonRpcHandler._handleRequest (/home/aymen/karak/account-abstraction/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:191:20)
      at async JsonRpcHandler._handleSingleRequest (/home/aymen/karak/account-abstraction/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:152:17)

eth_maxPriorityFeePerGas - Method not supported
```

also the test returns this 

```
Finalized userOp:  {
  sender: '0x2C6626618678dE393f0A0467E960B34Aaab969Be',
  nonce: 0,
  initCode: '0x9406cc6185a346906296840746125a0e449764545fbfb9cf000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000000000000000000000',
  callData: '0xb61d27f6000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa9604500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000',
  callGasLimit: '0x2dc6c0',
  verificationGasLimit: '0x2dc6c0',
  preVerificationGas: '0x1e8480',
  maxFeePerGas: '0x77359400',
  maxPriorityFeePerGas: '0x3b9aca00',
  paymasterAndData: '0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc900000000000000000000000000000000000000000000000000000000653f6a3600000000000000000000000000000000000000000000000000000000653f690a2eb245857fd6d390bf9779fc788b52d4650c92036fc8493523eb6f5d9573fb91679e0f8a7236044cab8107ca1066252fa9ce847223bb033d52f920364b26737b1b',
  signature: '0xb4dd6811c1589472500bc5c9368a1ce159c916c31e0521954900d9feb4addc821329da7a8a15a663b4055b315fb402c65ede38ae8c6f65e8659b89f6c16293361b'
}
Gas estimation result:  undefined
Result (userOpHash):  undefined
```

**Comment by norswap** [comment]
Hey there! Thanks for trying out roll-op.

I guess the first thing to figure out is whether this is an issue with eth-infinitism paymaster or with how set it up.

@eerkaijun Does the issue here seem familiar / any inkling of what might be going on?

I'm a little bit short on time at the moment, but I will try to look into this before the end of November if we can't figure it out otherwise.

**Comment by eerkaijun** [comment]
I haven't seen this error before. Agree that if you can provide the commands you run and the inputs (e.g. UserOp that runs into this error), might be easier to debug. 

Another possible reason is that you are running a hardhat node and it is not supporting the `eth_maxPriorityFeePerGas` RPC

**Comment by eerkaijun** [comment]
Seems like you have reached the maximum limit of RPC calls to your stackup bundler.
